# Generated by Django 3.1.2 on 2020-10-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_auto_20200819_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=100),
        ),
    ]
